name: Build Release

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
            goos: linux
            goarch: amd64
            output: file-organizer-linux-amd64

          - os: linux
            arch: arm64
            goos: linux
            goarch: arm64
            output: file-organizer-linux-arm64

          - os: macos
            arch: amd64
            goos: darwin
            goarch: amd64
            output: file-organizer-macos-amd64

          - os: macos
            arch: arm64
            goos: darwin
            goarch: arm64
            output: file-organizer-macos-arm64

          - os: windows
            arch: amd64
            goos: windows
            goarch: amd64
            output: file-organizer-windows-amd64.exe

          - os: windows
            arch: arm64
            goos: windows
            goarch: arm64
            output: file-organizer-windows-arm64.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          cache: true

      - name: Get dependencies
        run: go mod download

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: |
          go build -v -trimpath -ldflags="-s -w" -o ${{ matrix.output }} .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.output }}
          path: ${{ matrix.output }}
          retention-days: 5

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Prepare release assets
        run: |
          mkdir -p release
          find ./artifacts -type f -exec cp {} ./release/ \;
          ls -lh ./release/

      - name: Create checksums
        run: |
          cd release
          sha256sum * > SHA256SUMS
          cat SHA256SUMS

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
